name: Publish Python distributions to PyPI

on:
  pull_request:
    type: [closed]
    branches:
      - main

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: update version
        run: python get_latest_version.py
      - name: Install development dependencies
        if: github.event.pull_request.merged == true
        run: |
          pip install twine
          pip install pexpect
      - name: package module
        if: github.event.pull_request.merged == true
        run: python setup.py sdist
      - name: deploy to pypi
        if: github.event.pull_request.merged == true
        env:
          TWINE_USERNAME: ${{secrets.TWINE_USERNAME}}
          TWINE_PASSWORD: ${{secrets.TWINE_PASSWORD}}
        run: |
          twine upload dist/*
